### PR TITLE
Added background images based on weather

### PR DESCRIPTION
**Pull request by march93**

### CODE REVIEW

**Comment by M0nica** [comment]
Hi @march93 thank you for this contribution. For some reason I am not able to view the background images in the app. Can you pull the latest changes from this branch locally (I updated to resolve merge conflicts) and see if you still able to view the images?

**Comment by march93** [comment]
Hi @M0nica, for sure I'll take a look. I'm running into some problems trying to install the dependencies and I was wondering if you had any insight into that? I'm running Python 3.7 and Pip 18.1

**Comment by M0nica** [comment]
> Hi @M0nica, for sure I'll take a look. I'm running into some problems trying to install the dependencies and I was wondering if you had any insight into that? I'm running Python 3.7 and Pip 18.1

What happens when you run `pip install -r requirements.txt`?

**Comment by march93** [comment]
I ran the app on a different macbook with Python 3.6 and that worked for me for some reason. The background images shows up for me


screen shot 2018-10-23 at 9 34 05 am

**Pull request closed without merging**
